[package]
name = "jda-nas-rust"
version = "0.1.0"
authors = ["JellyBrick"]
edition = "2018"

[lib]
crate_type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jni = "0.16.0"
tokio = "0.2.19"